name: Love Comment

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'ç•™è¨€å†…å®¹'
        required: true
        default: 'ä½ å¥½å‘€ï¼Œè¿™æ˜¯é»˜è®¤ç•™è¨€'

jobs:
  post_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Post love letter to å°ç‹ç‹¸ ğŸ¦Š
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const issue_number = 1;
            const body = `${{ github.event.inputs.message }}`;
            await github.rest.issues.createComment({
              owner: 'sharky010309',
              repo: 'azhoufoxstar-comments',
              issue_number,
              body,
            });