name: Love Comment

on:
  repository_dispatch:
    types: [love_message]

jobs:
  post_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Post love letter to å°ç‹ç‹¸ ğŸ¦Š
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const issue_number = 1;
            const body = context.payload.client_payload.message;

            await github.rest.issues.createComment({
              owner: 'sharky010309',
              repo: 'azhoufoxstar-comments',
              issue_number,
              body,
            });